In [31]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [32]:
from Optimizer import Optimizer

In [33]:
import argparse
import datetime
import math
import os
from time import time
from typing import Any, List, Tuple

#import mlflow
import numpy as np
import pandas as pd
import torch
from joblib import Parallel, delayed
from loguru import logger
from sparsemax import Sparsemax

from artifacts import (
    build_plot_df_wrapper,
    save_csv_artifact,
    save_plot_strategy,
)
from BayesianOptimizer import BoTorchOptimizer, BoTorchOptimizerVariableStake
from data import (
    apply_final_treatment,
    join_metadata,
    load_metadata_artefacts,
    load_odds,
)
from dependencies.config import load_config
#from dependencies.utils import softmax
from filter import filter_by_linear_combination
from GameProbs import GameProbs

config = load_config("config/config.yml")


def setup(args):
    metadata, gameid_to_outcome = load_metadata_artefacts(config.metadata_path)
    odds = load_odds(config.odds_path, args.bookmakers)
    odds = join_metadata(odds, metadata)

    odds = odds.sort_values(["Datetime", "GameId"], ascending=True)

    odds = odds[
        (odds.Datetime.apply(str) >= args.date_start)
        & (odds.Datetime.apply(str) < args.date_end)
    ]

    return odds, gameid_to_outcome

In [34]:
#args = parser.parse_args()
parser = argparse.ArgumentParser()
parser.add_argument(
    "--date_start",
    type=str,
    default="2019-01-01",
    help="start date of the dataset",
)
parser.add_argument(
    "--date_end",
    type=str,
    default="2024-01-01",
    help="end date of the dataset",
)
parser.add_argument(
    "--bookmakers",
    nargs="+",
    default=None,
    help="A list of strings",
)
parser.add_argument(
    "--aggregator", type=str, help="aggregate by GameId or by Datetime"
)
parser.add_argument(
    "--min_games",
    type=int,
    default=1,
    help="threshold of minimum number of games to enter the optimization task",
)
parser.add_argument(
    "--bets_per_game", type=int, default=5, help="number of bets per game"
)
parser.add_argument(
    "--weight",
    type=float,
    default=0.5,
    help="weight of the linear combination filter",
)
parser.add_argument(
    "--optimizer",
    type=str,
    default="BoTorchOptimizer",
    help="optimizer to use",
)
parser.add_argument(
    "--probability_mapping",
    type=str,
    default="softmax",
    help="probability mapping function to use",
)
parser.add_argument(
    "--n_iterations",
    type=int,
    default=100,
    help="number of iterations to run the optimization task",
)
parser.add_argument(
    "--do_baseline",
    action="store_true",
    help="flag to apply baseline logic or not, not specifying the argument return the opposite of the action",
)
parser.add_argument(
    "--n_jobs",
    type=int,
    default=1,
    help="number of jobs to run in parallel",
)
parser.add_argument(
    "--save_experiment",
    action="store_true",
    help="flag to save the experiment artefacts, not specifying the argument return the opposite of the action",
)
args = parser.parse_args([
"--aggregator", "Datetime",
"--min_games", "1",
"--bets_per_game", "2",
"--n_iterations", "10",
"--weight", "0.5",
"--date_start", "2019-06-01",
"--date_end", "2019-12-01",
#"--do_baseline", "False"
#"--save_experiment"
])
print(args)

odds, gameid_to_outcome = setup(args)

grouped = odds.groupby(args.aggregator)

Namespace(date_start='2019-06-01', date_end='2019-12-01', bookmakers=None, aggregator='Datetime', min_games=1, bets_per_game=2, weight=0.5, optimizer='BoTorchOptimizer', probability_mapping='softmax', n_iterations=10, do_baseline=False, n_jobs=1, save_experiment=False)

In [35]:
for a ,b in grouped:
    print(a)
    print(b)

2019-06-01
        GameId Sportsbook      Market Scenario    Bet     Odd  public_prob  \
56978  2782628     Bet365         h2h            home    1.45     0.689655
56979  2782628     Bet365         h2h            draw    4.00     0.250000
56980  2782628     Bet365         h2h            away    7.50     0.133333
56981  2782628     Bet365  over/under      0.5   over    1.06     0.943396
56982  2782628     Bet365  over/under      0.5  under   10.00     0.100000
...        ...        ...         ...      ...    ...     ...          ...
59081  2782629  NordicBet       exact    5 : 0      o  175.00     0.005714
59082  2782629  NordicBet       exact    5 : 1      o  200.00     0.005000
59083  2782629  NordicBet       exact    6 : 0      o  250.00     0.004000
59084  2782629  NordicBet  both_score             yes    2.26     0.442478
59085  2782629  NordicBet  both_score              no    1.58     0.632911

           Home       Away    Datetime
56978  Flamengo  Fortaleza  2019-06-01
56979  Flamengo  Fortaleza  2019-06-01
56980  Flamengo  Fortaleza  2019-06-01
56981  Flamengo  Fortaleza  2019-06-01
56982  Flamengo  Fortaleza  2019-06-01
...         ...        ...         ...
59081     Bahia     Grêmio  2019-06-01
59082     Bahia     Grêmio  2019-06-01
59083     Bahia     Grêmio  2019-06-01
59084     Bahia     Grêmio  2019-06-01
59085     Bahia     Grêmio  2019-06-01

[2108 rows x 10 columns]
2019-06-02
        GameId Sportsbook      Market Scenario    Bet     Odd  public_prob  \
59086  2784078     Bet365         h2h            home    2.15     0.465116
59087  2784078     Bet365         h2h            draw    3.10     0.322581
59088  2784078     Bet365         h2h            away    3.40     0.294118
59089  2784078     Bet365  over/under      0.5   over    1.10     0.909091
59090  2784078     Bet365  over/under      0.5  under    7.50     0.133333
...        ...        ...         ...      ...    ...     ...          ...
63978  2784095  NordicBet       exact    5 : 0      o   45.00     0.022222
63979  2784095  NordicBet       exact    5 : 1      o   70.00     0.014286
63980  2784095  NordicBet       exact    6 : 0      o  100.00     0.010000
63981  2784095  NordicBet  both_score             yes    2.26     0.442478
63982  2784095  NordicBet  both_score              no    1.58     0.632911

                   Home           Away    Datetime
59086          Botafogo  Vasco da Gama  2019-06-02
59087          Botafogo  Vasco da Gama  2019-06-02
59088          Botafogo  Vasco da Gama  2019-06-02
59089          Botafogo  Vasco da Gama  2019-06-02
59090          Botafogo  Vasco da Gama  2019-06-02
...                 ...            ...         ...
63978  Atlético Mineiro            CSA  2019-06-02
63979  Atlético Mineiro            CSA  2019-06-02
63980  Atlético Mineiro            CSA  2019-06-02
63981  Atlético Mineiro            CSA  2019-06-02
63982  Atlético Mineiro            CSA  2019-06-02

[6934 rows x 10 columns]
2019-06-07
        GameId Sportsbook      Market Scenario    Bet     Odd  public_prob  \
66020  2789461     Bet365         h2h            home    2.90     0.344828
66021  2789461     Bet365         h2h            draw    3.10     0.322581
66022  2789461     Bet365         h2h            away    2.50     0.400000
66023  2789461     Bet365  over/under      0.5   over    1.10     0.909091
66024  2789461     Bet365  over/under      0.5  under    7.00     0.142857
...        ...        ...         ...      ...    ...     ...          ...
67167  2789461  NordicBet       exact    5 : 0      o  225.00     0.004444
67168  2789461  NordicBet       exact    5 : 1      o  225.00     0.004444
67169  2789461  NordicBet       exact    6 : 0      o  250.00     0.004000
67170  2789461  NordicBet  both_score             yes    2.05     0.487805
67171  2789461  NordicBet  both_score              no    1.70     0.588235

                Home           Away    Datetime
66020  Vasco da Gama  Internacional  2019-06-07
66021  Vasco da Gama  Internacional  2019-06-07
66022  Vasco da Gama  Internacional  2019-06-07
66023  Vasco da Gama  Internacional  2019-06-07
66024  Vasco da Gama  Internacional  2019-06-07
...              ...            ...         ...
67167  Vasco da Gama  Internacional  2019-06-07
67168  Vasco da Gama  Internacional  2019-06-07
67169  Vasco da Gama  Internacional  2019-06-07
67170  Vasco da Gama  Internacional  2019-06-07
67171  Vasco da Gama  Internacional  2019-06-07

[1152 rows x 10 columns]
2019-06-08
        GameId Sportsbook      Market Scenario    Bet     Odd  public_prob  \
69883  2790510     Bet365         h2h            home    2.40     0.416667
69884  2790510     Bet365         h2h            draw    3.00     0.333333
69885  2790510     Bet365         h2h            away    3.20     0.312500
69886  2790510     Bet365  over/under      0.5   over    1.12     0.892857
69887  2790510     Bet365  over/under      0.5  under    6.00     0.166667
...        ...        ...         ...      ...    ...     ...          ...
69088  2791672  NordicBet       exact    5 : 0      o  125.00     0.008000
69089  2791672  NordicBet       exact    5 : 1      o  150.00     0.006667
69090  2791672  NordicBet       exact    6 : 0      o  225.00     0.004444
69091  2791672  NordicBet  both_score             yes    2.45     0.408163
69092  2791672  NordicBet  both_score              no    1.50     0.666667

           Home         Away    Datetime
69883     Ceará        Bahia  2019-06-08
69884     Ceará        Bahia  2019-06-08
69885     Ceará        Bahia  2019-06-08
69886     Ceará        Bahia  2019-06-08
69887     Ceará        Bahia  2019-06-08
...         ...          ...         ...
69088  Cruzeiro  Corinthians  2019-06-08
69089  Cruzeiro  Corinthians  2019-06-08
69090  Cruzeiro  Corinthians  2019-06-08
69091  Cruzeiro  Corinthians  2019-06-08
69092  Cruzeiro  Corinthians  2019-06-08

[3636 rows x 10 columns]
2019-06-09
        GameId Sportsbook      Market Scenario    Bet     Odd  public_prob  \
73839  2790511     Bet365         h2h            home    1.66     0.602410
73840  2790511     Bet365         h2h            draw    4.00     0.250000
73841  2790511     Bet365         h2h            away    4.75     0.210526
73842  2790511     Bet365  over/under      0.5   over    1.05     0.952381
73843  2790511     Bet365  over/under      0.5  under   11.00     0.090909
...        ...        ...         ...      ...    ...     ...          ...
72836  2791673  NordicBet       exact    5 : 0      o  225.00     0.004444
72837  2791673  NordicBet       exact    5 : 1      o  225.00     0.004444
72838  2791673  NordicBet       exact    6 : 0      o  250.00     0.004000
72839  2791673  NordicBet  both_score             yes    2.15     0.465116
72840  2791673  NordicBet  both_score              no    1.64     0.609756

         Home              Away    Datetime
73839  Santos  Atlético Mineiro  2019-06-09
73840  Santos  Atlético Mineiro  2019-06-09
73841  Santos  Atlético Mineiro  2019-06-09
73842  Santos  Atlético Mineiro  2019-06-09
73843  Santos  Atlético Mineiro  2019-06-09
...       ...               ...         ...
72836     CSA          Botafogo  2019-06-09
72837     CSA          Botafogo  2019-06-09
72838     CSA          Botafogo  2019-06-09
72839     CSA          Botafogo  2019-06-09
72840     CSA          Botafogo  2019-06-09

[4172 rows x 10 columns]
2019-06-10
        GameId Sportsbook      Market Scenario    Bet     Odd  public_prob  \
74980  2792417     Bet365         h2h            home    1.85     0.540541
74981  2792417     Bet365         h2h            draw    3.40     0.294118
74982  2792417     Bet365         h2h            away    4.33     0.230947
74983  2792417     Bet365  over/under      0.5   over    1.10     0.909091
74984  2792417     Bet365  over/under      0.5  under    7.50     0.133333
...        ...        ...         ...      ...    ...     ...          ...
76102  2792417  NordicBet       exact    5 : 0      o   95.00     0.010526
76103  2792417  NordicBet       exact    5 : 1      o  100.00     0.010000
76104  2792417  NordicBet       exact    6 : 0      o  200.00     0.005000
76105  2792417  NordicBet  both_score             yes    2.10     0.476190
76106  2792417  NordicBet  both_score              no    1.67     0.598802

        Home         Away    Datetime
74980  Goiás  Chapecoense  2019-06-10
74981  Goiás  Chapecoense  2019-06-10
74982  Goiás  Chapecoense  2019-06-10
74983  Goiás  Chapecoense  2019-06-10
74984  Goiás  Chapecoense  2019-06-10
...      ...          ...         ...
76102  Goiás  Chapecoense  2019-06-10
76103  Goiás  Chapecoense  2019-06-10
76104  Goiás  Chapecoense  2019-06-10
76105  Goiás  Chapecoense  2019-06-10
76106  Goiás  Chapecoense  2019-06-10

[1127 rows x 10 columns]
2019-06-12
        GameId Sportsbook      Market Scenario    Bet     Odd  public_prob  \
76107  2794083     Bet365         h2h            home    3.20     0.312500
76108  2794083     Bet365         h2h            draw    3.00     0.333333
76109  2794083     Bet365         h2h            away    2.40     0.416667
76110  2794083     Bet365  over/under      0.5   over    1.11     0.900901
76111  2794083     Bet365  over/under      0.5  under    6.50     0.153846
...        ...        ...         ...      ...    ...     ...          ...
77066  2794083  NordicBet       exact    5 : 0      o  225.00     0.004444
77067  2794083  NordicBet       exact    5 : 1      o  225.00     0.004444
77068  2794083  NordicBet       exact    6 : 0      o  250.00     0.004000
77069  2794083  NordicBet  both_score             yes    2.00     0.500000
77070  2794083  NordicBet  both_score              no    1.74     0.574713

           Home    Away    Datetime
76107  Botafogo  Grêmio  2019-06-12
76108  Botafogo  Grêmio  2019-06-12
76109  Botafogo  Grêmio  2019-06-12
76110  Botafogo  Grêmio  2019-06-12
76111  Botafogo  Grêmio  2019-06-12
...         ...     ...         ...
77066  Botafogo  Grêmio  2019-06-12
77067  Botafogo  Grêmio  2019-06-12
77068  Botafogo  Grêmio  2019-06-12
77069  Botafogo  Grêmio  2019-06-12
77070  Botafogo  Grêmio  2019-06-12

[964 rows x 10 columns]
2019-06-13
        GameId Sportsbook      Market Scenario    Bet     Odd  public_prob  \
77071  2795195     Bet365         h2h            home    3.00     0.333333
77072  2795195     Bet365         h2h            draw    3.00     0.333333
77073  2795195     Bet365         h2h            away    2.50     0.400000
77074  2795195     Bet365  over/under      0.5   over    1.11     0.900901
77075  2795195     Bet365  over/under      0.5  under    6.50     0.153846
...        ...        ...         ...      ...    ...     ...          ...
84990  2795203  NordicBet       exact    5 : 0      o  200.00     0.005000
84991  2795203  NordicBet       exact    5 : 1      o  175.00     0.005714
84992  2795203  NordicBet       exact    6 : 0      o  250.00     0.004000
84993  2795203  NordicBet  both_score             yes    1.83     0.546448
84994  2795203  NordicBet  both_score              no    1.90     0.526316

            Home          Away    Datetime
77071  Fortaleza      Cruzeiro  2019-06-13
77072  Fortaleza      Cruzeiro  2019-06-13
77073  Fortaleza      Cruzeiro  2019-06-13
77074  Fortaleza      Cruzeiro  2019-06-13
77075  Fortaleza      Cruzeiro  2019-06-13
...          ...           ...         ...
84990      Goiás  Athletico-PR  2019-06-13
84991      Goiás  Athletico-PR  2019-06-13
84992      Goiás  Athletico-PR  2019-06-13
84993      Goiás  Athletico-PR  2019-06-13
84994      Goiás  Athletico-PR  2019-06-13

[8898 rows x 10 columns]
2019-07-13
        GameId Sportsbook      Market Scenario    Bet     Odd  public_prob  \
86939  2823105     Bet365         h2h            home    1.61     0.621118
86940  2823105     Bet365         h2h            draw    3.60     0.277778
86941  2823105     Bet365         h2h            away    6.00     0.166667
86942  2823105     Bet365  over/under      0.5   over    1.08     0.925926
86943  2823105     Bet365  over/under      0.5  under    8.00     0.125000
...        ...        ...         ...      ...    ...     ...          ...
86934  2823108  NordicBet       exact    5 : 0      o  125.00     0.008000
86935  2823108  NordicBet       exact    5 : 1      o  125.00     0.008000
86936  2823108  NordicBet       exact    6 : 0      o  225.00     0.004444
86937  2823108  NordicBet  both_score             yes    2.25     0.444444
86938  2823108  NordicBet  both_score              no    1.59     0.628931

            Home           Away    Datetime
86939     Grêmio  Vasco da Gama  2019-07-13
86940     Grêmio  Vasco da Gama  2019-07-13
86941     Grêmio  Vasco da Gama  2019-07-13
86942     Grêmio  Vasco da Gama  2019-07-13
86943     Grêmio  Vasco da Gama  2019-07-13
...          ...            ...         ...
86934  Fortaleza           Avaí  2019-07-13
86935  Fortaleza           Avaí  2019-07-13
86936  Fortaleza           Avaí  2019-07-13
86937  Fortaleza           Avaí  2019-07-13
86938  Fortaleza           Avaí  2019-07-13

[3731 rows x 10 columns]
2019-07-14
        GameId Sportsbook      Market Scenario    Bet     Odd  public_prob  \
89700  2823109     Bet365         h2h            home    1.25     0.800000
89701  2823109     Bet365         h2h            draw    5.25     0.190476
89702  2823109     Bet365         h2h            away   15.00     0.066667
89703  2823109     Bet365  over/under      0.5   over    1.04     0.961538
89704  2823109     Bet365  over/under      0.5  under   13.00     0.076923
...        ...        ...         ...      ...    ...     ...          ...
94933  2823113  NordicBet       exact    5 : 0      o  175.00     0.005714
94934  2823113  NordicBet       exact    5 : 1      o  175.00     0.005714
94935  2823113  NordicBet       exact    6 : 0      o  250.00     0.004000
94936  2823113  NordicBet  both_score             yes    2.00     0.500000
94937  2823113  NordicBet  both_score              no    1.74     0.574713

              Home              Away    Datetime
89700     Flamengo             Goiás  2019-07-14
89701     Flamengo             Goiás  2019-07-14
89702     Flamengo             Goiás  2019-07-14
89703     Flamengo             Goiás  2019-07-14
89704     Flamengo             Goiás  2019-07-14
...            ...               ...         ...
94933  Chapecoense  Atlético Mineiro  2019-07-14
94934  Chapecoense  Atlético Mineiro  2019-07-14
94935  Chapecoense  Atlético Mineiro  2019-07-14
94936  Chapecoense  Atlético Mineiro  2019-07-14
94937  Chapecoense  Atlético Mineiro  2019-07-14

[5238 rows x 10 columns]
2019-07-15
        GameId Sportsbook      Market Scenario    Bet     Odd  public_prob  \
94938  2827638     Bet365         h2h            home    1.65     0.606061
94939  2827638     Bet365         h2h            draw    3.60     0.277778
94940  2827638     Bet365         h2h            away    5.50     0.181818
94941  2827638     Bet365  over/under      0.5   over    1.08     0.925926
94942  2827638     Bet365  over/under      0.5  under    8.00     0.125000
...        ...        ...         ...      ...    ...     ...          ...
96078  2827638  NordicBet       exact    5 : 0      o   70.00     0.014286
96079  2827638  NordicBet       exact    5 : 1      o   90.00     0.011111
96080  2827638  NordicBet       exact    6 : 0      o  150.00     0.006667
96081  2827638  NordicBet  both_score             yes    2.14     0.467290
96082  2827638  NordicBet  both_score              no    1.64     0.609756

             Home   Away    Datetime
94938  Fluminense  Ceará  2019-07-15
94939  Fluminense  Ceará  2019-07-15
94940  Fluminense  Ceará  2019-07-15
94941  Fluminense  Ceará  2019-07-15
94942  Fluminense  Ceará  2019-07-15
...           ...    ...         ...
96078  Fluminense  Ceará  2019-07-15
96079  Fluminense  Ceará  2019-07-15
96080  Fluminense  Ceará  2019-07-15
96081  Fluminense  Ceará  2019-07-15
96082  Fluminense  Ceará  2019-07-15

[1145 rows x 10 columns]
2019-07-20
         GameId Sportsbook      Market Scenario    Bet     Odd  public_prob  \
96083   2832536     Bet365         h2h            home    2.30     0.434783
96084   2832536     Bet365         h2h            draw    3.10     0.322581
96085   2832536     Bet365         h2h            away    3.25     0.307692
96086   2832536     Bet365  over/under      0.5   over    1.08     0.925926
96087   2832536     Bet365  over/under      0.5  under    8.50     0.117647
...         ...        ...         ...      ...    ...     ...          ...
100510  2832546  NordicBet       exact    5 : 0      o  225.00     0.004444
100511  2832546  NordicBet       exact    5 : 1      o  225.00     0.004444
100512  2832546  NordicBet       exact    6 : 0      o  250.00     0.004000
100513  2832546  NordicBet  both_score             yes    1.90     0.526316
100514  2832546  NordicBet  both_score              no    1.83     0.546448

                 Home          Away    Datetime
96083   Vasco da Gama    Fluminense  2019-07-20
96084   Vasco da Gama    Fluminense  2019-07-20
96085   Vasco da Gama    Fluminense  2019-07-20
96086   Vasco da Gama    Fluminense  2019-07-20
96087   Vasco da Gama    Fluminense  2019-07-20
...               ...           ...         ...
100510            CSA  Athletico-PR  2019-07-20
100511            CSA  Athletico-PR  2019-07-20
100512            CSA  Athletico-PR  2019-07-20
100513            CSA  Athletico-PR  2019-07-20
100514            CSA  Athletico-PR  2019-07-20

[5399 rows x 10 columns]
2019-07-21
         GameId Sportsbook      Market Scenario    Bet     Odd  public_prob  \
101482  2833635     Bet365         h2h            home    3.75     0.266667
101483  2833635     Bet365         h2h            draw    3.00     0.333333
101484  2833635     Bet365         h2h            away    2.15     0.465116
101485  2833635     Bet365  over/under      0.5   over    1.10     0.909091
101486  2833635     Bet365  over/under      0.5  under    7.50     0.133333
...         ...        ...         ...      ...    ...     ...          ...
105345  2833642  NordicBet       exact    5 : 0      o  100.00     0.010000
105346  2833642  NordicBet       exact    5 : 1      o  125.00     0.008000
105347  2833642  NordicBet       exact    6 : 0      o  225.00     0.004444
105348  2833642  NordicBet  both_score             yes    2.09     0.478469
105349  2833642  NordicBet  both_score              no    1.67     0.598802

            Home    Away    Datetime
101482  Botafogo  Santos  2019-07-21
101483  Botafogo  Santos  2019-07-21
101484  Botafogo  Santos  2019-07-21
101485  Botafogo  Santos  2019-07-21
101486  Botafogo  Santos  2019-07-21
...          ...     ...         ...
105345      Avaí   Goiás  2019-07-21
105346      Avaí   Goiás  2019-07-21
105347      Avaí   Goiás  2019-07-21
105348      Avaí   Goiás  2019-07-21
105349      Avaí   Goiás  2019-07-21

[3868 rows x 10 columns]
2019-07-22
         GameId Sportsbook      Market Scenario    Bet     Odd  public_prob  \
105350  2834402     Bet365         h2h            home    1.50     0.666667
105351  2834402     Bet365         h2h            draw    3.75     0.266667
105352  2834402     Bet365         h2h            away    7.50     0.133333
105353  2834402     Bet365  over/under      0.5   over    1.08     0.925926
105354  2834402     Bet365  over/under      0.5  under    8.00     0.125000
...         ...        ...         ...      ...    ...     ...          ...
106489  2834402  NordicBet       exact    5 : 0      o   55.00     0.018182
106490  2834402  NordicBet       exact    5 : 1      o   80.00     0.012500
106491  2834402  NordicBet       exact    6 : 0      o  125.00     0.008000
106492  2834402  NordicBet  both_score             yes    2.28     0.438596
106493  2834402  NordicBet  both_score              no    1.57     0.636943

             Home         Away    Datetime
105350  São Paulo  Chapecoense  2019-07-22
105351  São Paulo  Chapecoense  2019-07-22

In [36]:
# Function to get the n-th group and its DataFrame
def get_nth_group(grouped, n):
    for i, (group_key, group_df) in enumerate(grouped):
        if i == n:
            return group_key, group_df
    raise IndexError("Group index out of range")
n = 0
group = get_nth_group(grouped, n)

In [37]:
date, group_data = group
print(date)

2019-06-01

In [38]:
games_ids = group_data.GameId.unique()
print(games_ids)

['2782628' '2782629']

In [39]:
odds

,GameId,Sportsbook,Market,Scenario,Bet,Odd,public_prob,Home,Away,Datetime
56978,2782628,Bet365,h2h,,home,1.45,0.689655,Flamengo,Fortaleza,2019-06-01
56979,2782628,Bet365,h2h,,draw,4.00,0.250000,Flamengo,Fortaleza,2019-06-01
56980,2782628,Bet365,h2h,,away,7.50,0.133333,Flamengo,Fortaleza,2019-06-01
56981,2782628,Bet365,over/under,0.5,over,1.06,0.943396,Flamengo,Fortaleza,2019-06-01
56982,2782628,Bet365,over/under,0.5,under,10.00,0.100000,Flamengo,Fortaleza,2019-06-01
...,...,...,...,...,...,...,...,...,...,...
366561,3010529,NordicBet,exact,5 : 0,o,100.00,0.010000,Ceará,Athletico-PR,2019-11-30
366562,3010529,NordicBet,exact,5 : 1,o,100.00,0.010000,Ceará,Athletico-PR,2019-11-30
366563,3010529,NordicBet,exact,6 : 0,o,125.00,0.008000,Ceará,Athletico-PR,2019-11-30
366564,3010529,NordicBet,both_score,,yes,1.97,0.507614,Ceará,Athletico-PR,2019-11-30
366565,3010529,NordicBet,both_score,,no,1.76,0.568182,Ceará,Athletico-PR,2019-11-30

In [9]:
# metadata, gameid_to_outcome = load_metadata_artefacts("data/metadata-with-date-new.parquet")
# odds = load_odds("data/odds-new-correct.parquet")
# odds = join_metadata(odds, metadata)
# print(metadata.shape)
# print(odds.shape)

In [10]:
# from data import load_map
# data = load_map("data/meanSurface-new.json")

In [40]:
GAME_ID = "7290395" # Chapecoense x Flamengo
my_game = GameProbs(GAME_ID) 
df = my_game.build_dataframe()
df

        0       1       2       3       4       5       6
0  0.0245  0.0006  0.0017  0.0035  0.0058  0.0085  0.1814
1  0.0002  0.0250  0.0029  0.0057  0.0093  0.0130  0.2223
2  0.0002  0.0011  0.0146  0.0054  0.0085  0.0116  0.1732
3  0.0002  0.0009  0.0022  0.0078  0.0061  0.0081  0.1089
4  0.0001  0.0006  0.0014  0.0025  0.0047  0.0049  0.0602
5  0.0001  0.0003  0.0008  0.0014  0.0021  0.0029  0.0306
6  0.0001  0.0004  0.0009  0.0015  0.0021  0.0026  0.0264

In [12]:
group_data

,GameId,Sportsbook,Market,Scenario,Bet,Odd,public_prob,Home,Away,Datetime
56978,2782628,Bet365,h2h,,home,1.45,0.689655,Flamengo,Fortaleza,2019-06-01
56979,2782628,Bet365,h2h,,draw,4.00,0.250000,Flamengo,Fortaleza,2019-06-01
56980,2782628,Bet365,h2h,,away,7.50,0.133333,Flamengo,Fortaleza,2019-06-01
56981,2782628,Bet365,over/under,0.5,over,1.06,0.943396,Flamengo,Fortaleza,2019-06-01
56982,2782628,Bet365,over/under,0.5,under,10.00,0.100000,Flamengo,Fortaleza,2019-06-01
...,...,...,...,...,...,...,...,...,...,...
59081,2782629,NordicBet,exact,5 : 0,o,175.00,0.005714,Bahia,Grêmio,2019-06-01
59082,2782629,NordicBet,exact,5 : 1,o,200.00,0.005000,Bahia,Grêmio,2019-06-01
59083,2782629,NordicBet,exact,6 : 0,o,250.00,0.004000,Bahia,Grêmio,2019-06-01
59084,2782629,NordicBet,both_score,,yes,2.26,0.442478,Bahia,Grêmio,2019-06-01
59085,2782629,NordicBet,both_score,,no,1.58,0.632911,Bahia,Grêmio,2019-06-01

In [13]:
#GAME_ID = '2738735'
#odds_sample = group_data[(group_data.GameId==GAME_ID)]
odds_sample = group_data
#odds_sample = join_metadata(odds_sample, metadata)
#games_ids = odds_sample['GameId'].unique()
print(games_ids)

# Initialize dict to store dataframes of favorable bet opportunities
odds_dict = {}
# Initialize dict to store 7x7 matrices/dataframes of real probabilities 
df_probs_dict = {}

for game_id in games_ids:
    df = GameProbs(game_id).build_dataframe()
    odds_sample = group_data[(group_data.GameId==game_id)]
    odds_sample = apply_final_treatment(df_odds=odds_sample, df_real_prob=df)
    odds_sample = filter_by_linear_combination(odds_sample, n=5)
    odds_dict[game_id] = odds_sample
    df_probs_dict[game_id] = df
odds_dt = pd.concat(odds_dict.values())

['2782628' '2782629']

In [14]:
len(df_probs_dict.values())

2

In [15]:
odds_sample = odds_sample[odds_sample.Market.isin(['spread', 'over/under', 'h2h', 'exact', 'both_score'])].reset_index(drop=True)
print(odds_sample.shape)

(4, 17)

In [16]:
n = len(odds_dt)
allocation_array = np.round(np.array(((1/n), ) * n), 4)
allocation_array

array([0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111,
       0.1111])

## COBYLA via Simulation Optimizer

In [17]:
from monte_carlo_return import (
    generate_bet_return,
    compute_objective_via_simulation,
)

In [18]:
games_ids

array(['2782628', '2782629'], dtype=object)

In [19]:
len(odds_dict)

2

In [20]:
n = len(odds_dt)
allocation_array = np.round(np.array(((1/n), ) * n), 4)
allocation_array

financial_return_array = generate_bet_return(
    df_prob=df_probs_dict,
    df_bet=odds_dt,
    num_simulations=10000,
    allocation_array=allocation_array
)
financial_return_array

array([0.687709 , 1.870924 , 1.3859725, ..., 0.6460465, 3.249675 ,
       1.3859725])

In [21]:
print(np.mean(financial_return_array))
print(np.std(financial_return_array))

1.1726516120000001
2.3527541642281093

In [22]:
games_ids

array(['2782628', '2782629'], dtype=object)

In [23]:
compute_objective_via_simulation(
    x=allocation_array,
    df_prob=df_probs_dict,
    df_bet=odds_dt,
    num_simulations=10000
)

-0.48073276322967534

In [24]:
solution, value, time_limit_flag = Optimizer().run_optimization(
    fun=compute_objective_via_simulation,
    x0=np.zeros(len(odds_dt)),
    args=(df_probs_dict, odds_dt, 1000),
)
print(f"Value: {value}")

Value: -3.924314369779696
   Normal return from subroutine COBYLA


   NFVALS =  114   F =-3.924314E+00    MAXCV = 0.000000E+00
   X = 1.488675E+00   2.713398E+00   1.750020E+00   1.993636E+00  -1.666307E+00
       8.951997E-01  -5.212408E-01  -1.344915E+00  -2.914300E+00

In [26]:
value

-6.618251607544345

## COBYLA Analytical Optimizer

In [24]:
from analytical_return import compute_objective_via_analytical

In [25]:
odds_favorable = np.array(odds_dt['Odd'])
real_prob_favorable = np.array(odds_dt['real_prob'])
#scenario_favorable = np.array(odds_sample_favorable['Bet'])
event_favorable = list(odds_dt['BetMap'].values)
games_ids = np.array(odds_dt['GameId'])

In [26]:
len(games_ids)

9

In [31]:
# n = len(odds_dt)
# allocation_array = np.round(np.array(((1/n), ) * n), 4)
# allocation_array

In [32]:
allocation_array

array([0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111,
       0.1111])

In [33]:
compute_objective_via_analytical(
    x=np.zeros(len(odds_dt)),
    public_odd=odds_favorable,
    real_probabilities=real_prob_favorable,
    event=event_favorable,
    games_ids=games_ids,
    df_probs_dict=df_probs_dict,
)

-0.48152068573464457

In [34]:
solution, value, time_limit_flag = Optimizer().run_optimization(
    fun=compute_objective_via_analytical,
    x0=np.zeros(len(odds_favorable)),
    args=(odds_favorable, real_prob_favorable, event_favorable, games_ids, df_probs_dict)
)
print(f"Value: {value}")

Value: -6.965906207766195
   Return from subroutine COBYLA because the MAXFUN limit has been reached.


   NFVALS = 1000   F =-6.965906E+00    MAXCV = 0.000000E+00
   X = 4.572379E+00   2.105247E+00   1.509035E+00   2.129818E+00  -2.443923E-01
       3.172832E-01  -1.435522E+00  -2.498112E+00  -3.376482E+00

## LongTermOptimizer

In [27]:
len(odds_favorable) == len(odds_dt)

True

In [28]:
from LongTermOptimizer import estimate_long_term_return
solution, value, time_limit_flag = Optimizer().run_optimization(
    fun=estimate_long_term_return,
    x0=np.zeros(len(odds_dt)),
    args=(df_probs_dict, odds_dt, 100)
)
print(f"Value: {value}")

Value: -1.5048704186575604e+16
   Normal return from subroutine COBYLA


   NFVALS =   87   F =-1.504870E+16    MAXCV = 0.000000E+00
   X = 7.702248E-01   3.335832E+00   1.214765E+00  -5.862824E-01  -2.318410E+00
       1.001839E+00  -5.676557E-01  -7.775075E-02  -6.495089E-01

In [30]:
from dependencies.utils import softmax
assert len(solution) == len(odds_dt)
print(f"Sum of solution: {sum(solution)}")
solution = softmax(solution)
print(f"Sum of solution after softmax: {sum(solution)}")
print(solution)

Sum of solution: 2.123054062013594
Sum of solution after softmax: 1.0
[0.05535704 0.72011537 0.0863444  0.01425769 0.0025223  0.06978494
 0.01452575 0.02370837 0.01338414]