In [30]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [5]:
["a", "b", "c"][:4]

['a', 'b', 'c']

In [31]:
from Optimizer import Optimizer

In [32]:
import argparse
import datetime
import math
import os
from time import time
from typing import Any, List, Tuple

#import mlflow
import numpy as np
import pandas as pd
import torch
from joblib import Parallel, delayed
from loguru import logger
from sparsemax import Sparsemax

from artifacts import (
    build_plot_df_wrapper,
    save_csv_artifact,
    save_plot_strategy,
)
from BayesianOptimizer import BoTorchOptimizer, BoTorchOptimizerVariableStake
from data import (
    apply_final_treatment,
    join_metadata,
    load_metadata_artefacts,
    load_odds,
)
from dependencies.config import load_config
#from dependencies.utils import softmax
from filter import filter_by_linear_combination
from GameProbs import GameProbs

config = load_config("config/config.yml")


def setup(args):
    metadata, gameid_to_outcome = load_metadata_artefacts(config.metadata_path)
    odds = load_odds(config.odds_path, args.bookmakers)
    odds = join_metadata(odds, metadata)

    odds = odds.sort_values(["Datetime", "GameId"], ascending=True)

    odds = odds[
        (odds.Datetime.apply(str) >= args.date_start)
        & (odds.Datetime.apply(str) < args.date_end)
    ]

    return odds, gameid_to_outcome

In [33]:
#args = parser.parse_args()
parser = argparse.ArgumentParser()
parser.add_argument(
    "--date_start",
    type=str,
    default="2019-01-01",
    help="start date of the dataset",
)
parser.add_argument(
    "--date_end",
    type=str,
    default="2024-01-01",
    help="end date of the dataset",
)
parser.add_argument(
    "--bookmakers",
    nargs="+",
    default=None,
    help="A list of strings",
)
parser.add_argument(
    "--aggregator", type=str, help="aggregate by GameId or by Datetime"
)
parser.add_argument(
    "--min_games",
    type=int,
    default=1,
    help="threshold of minimum number of games to enter the optimization task",
)
parser.add_argument(
    "--bets_per_game", type=int, default=5, help="number of bets per game"
)
parser.add_argument(
    "--weight",
    type=float,
    default=0.5,
    help="weight of the linear combination filter",
)
parser.add_argument(
    "--optimizer",
    type=str,
    default="BoTorchOptimizer",
    help="optimizer to use",
)
parser.add_argument(
    "--probability_mapping",
    type=str,
    default="softmax",
    help="probability mapping function to use",
)
parser.add_argument(
    "--n_iterations",
    type=int,
    default=100,
    help="number of iterations to run the optimization task",
)
parser.add_argument(
    "--do_baseline",
    action="store_true",
    help="flag to apply baseline logic or not, not specifying the argument return the opposite of the action",
)
parser.add_argument(
    "--n_jobs",
    type=int,
    default=1,
    help="number of jobs to run in parallel",
)
parser.add_argument(
    "--save_experiment",
    action="store_true",
    help="flag to save the experiment artefacts, not specifying the argument return the opposite of the action",
)
args = parser.parse_args([
"--aggregator", "Datetime",
"--min_games", "1",
"--bets_per_game", "2",
"--n_iterations", "10",
"--weight", "0.5",
"--date_start", "2023-01-01",
"--date_end", "2024-01-01",
#"--do_baseline", "False"
#"--save_experiment"
])
print(args)

odds, gameid_to_outcome = setup(args)

grouped = odds.groupby(args.aggregator)

Namespace(date_start='2023-01-01', date_end='2024-01-01', bookmakers=None, aggregator='Datetime', min_games=1, bets_per_game=2, weight=0.5, optimizer='BoTorchOptimizer', probability_mapping='softmax', n_iterations=10, do_baseline=False, n_jobs=1, save_experiment=False)

In [34]:
for a ,b in grouped:
    print(a)
    print(b)

2023-04-15
          GameId     Sportsbook Market Scenario   Bet     Odd  public_prob  \
2079131  7290394      Stake.com    h2h           home    2.44     0.409836
2079132  7290394      Stake.com    h2h           draw    3.10     0.322581
2079133  7290394      Stake.com    h2h           away    3.10     0.322581
2079134  7290394  BC.Game Sport    h2h           home    2.46     0.406504
2079135  7290394  BC.Game Sport    h2h           draw    3.10     0.322581
...          ...            ...    ...      ...   ...     ...          ...
2036111  7290402        Midnite  exact   10 : 6     o  101.00     0.009901
2036112  7290402        Midnite  exact   10 : 7     o  101.00     0.009901
2036113  7290402        Midnite  exact   10 : 8     o  101.00     0.009901
2036114  7290402        Midnite  exact   10 : 9     o  101.00     0.009901
2036115  7290402        Midnite  exact  10 : 10     o  101.00     0.009901

               Home        Away    Datetime
2079131    Botafogo   São Paulo  2023-04-15
2079132    Botafogo   São Paulo  2023-04-15
2079133    Botafogo   São Paulo  2023-04-15
2079134    Botafogo   São Paulo  2023-04-15
2079135    Botafogo   São Paulo  2023-04-15
...             ...         ...         ...
2036111  América-MG  Fluminense  2023-04-15
2036112  América-MG  Fluminense  2023-04-15
2036113  América-MG  Fluminense  2023-04-15
2036114  América-MG  Fluminense  2023-04-15
2036115  América-MG  Fluminense  2023-04-15

[1298 rows x 10 columns]
2023-04-16
          GameId      Sportsbook Market Scenario   Bet     Odd  public_prob  \
2100318  7290393       Stake.com    h2h           home    1.38     0.724638
2100319  7290393       Stake.com    h2h           draw    4.80     0.208333
2100320  7290393       Stake.com    h2h           away    7.80     0.128205
2100321  7290393   BC.Game Sport    h2h           home    1.39     0.719424
2100322  7290393   BC.Game Sport    h2h           draw    4.90     0.204082
...          ...             ...    ...      ...   ...     ...          ...
2033596  7290399  LeoVegas Sport  exact    6 : 0     o  251.00     0.003984
2033597  7290399  LeoVegas Sport  exact    6 : 1     o  251.00     0.003984
2033598  7290399         Betobet  exact    6 : 2     o  501.00     0.001996
2033599  7290399         Betobet  exact    7 : 0     o  451.00     0.002217
2033600  7290399         Betobet  exact    7 : 1     o  501.00     0.001996

             Home      Away    Datetime
2100318  Flamengo  Coritiba  2023-04-16
2100319  Flamengo  Coritiba  2023-04-16
2100320  Flamengo  Coritiba  2023-04-16
2100321  Flamengo  Coritiba  2023-04-16
2100322  Flamengo  Coritiba  2023-04-16
...           ...       ...         ...
2033596    Grêmio    Santos  2023-04-16
2033597    Grêmio    Santos  2023-04-16
2033598    Grêmio    Santos  2023-04-16
2033599    Grêmio    Santos  2023-04-16
2033600    Grêmio    Santos  2023-04-16

[854 rows x 10 columns]
2023-04-22
          GameId      Sportsbook Market Scenario   Bet     Odd  public_prob  \
2078162  7290368   BC.Game Sport    h2h           home    2.55     0.392157
2078163  7290368   BC.Game Sport    h2h           draw    3.20     0.312500
2078164  7290368   BC.Game Sport    h2h           away    2.90     0.344828
2078165  7290368       Betwinner    h2h           home    2.34     0.427350
2078166  7290368       Betwinner    h2h           draw    3.26     0.306748
...          ...             ...    ...      ...   ...     ...          ...
2045511  7290405           20Bet  exact    6 : 0     o  100.00     0.010000
2045512  7290405  LeoVegas Sport  exact    6 : 1     o  151.00     0.006623
2045513  7290405       Parimatch  exact    6 : 2     o  251.00     0.003984
2045514  7290405       Parimatch  exact    7 : 0     o  300.00     0.003333
2045515  7290405       Parimatch  exact    7 : 1     o  300.00     0.003333

              Home                 Away    Datetime
2078162     Cuiabá  Red Bull Bragantino  2023-04-22
2078163     Cuiabá  Red Bull Bragantino  2023-04-22
2078164     Cuiabá  Red Bull Bragantino  2023-04-22
2078165     Cuiabá  Red Bull Bragantino  2023-04-22
2078166     Cuiabá  Red Bull Bragantino  2023-04-22
...            ...                  ...         ...
2045511  São Paulo           América-MG  2023-04-22
2045512  São Paulo           América-MG  2023-04-22
2045513  São Paulo           América-MG  2023-04-22
2045514  São Paulo           América-MG  2023-04-22
2045515  São Paulo           América-MG  2023-04-22

[654 rows x 10 columns]
2023-04-23
          GameId      Sportsbook Market Scenario   Bet     Odd  public_prob  \
2016099  7290354       Stake.com    h2h           home    2.65     0.377358
2016100  7290354       Stake.com    h2h           draw    2.95     0.338983
2016101  7290354       Stake.com    h2h           away    2.60     0.384615
2016102  7290354   BC.Game Sport    h2h           home    2.70     0.370370
2016103  7290354   BC.Game Sport    h2h           draw    3.25     0.307692
...          ...             ...    ...      ...   ...     ...          ...
2058422  7290408           20Bet  exact    5 : 1     o  100.00     0.010000
2058423  7290408  LeoVegas Sport  exact    5 : 2     o  251.00     0.003984
2058424  7290408         Betobet  exact    5 : 3     o  401.00     0.002494
2058425  7290408           20Bet  exact    6 : 0     o  100.00     0.010000
2058426  7290408         Betobet  exact    6 : 1     o  401.00     0.002494

                  Home      Away    Datetime
2016099  Internacional  Flamengo  2023-04-23
2016100  Internacional  Flamengo  2023-04-23
2016101  Internacional  Flamengo  2023-04-23
2016102  Internacional  Flamengo  2023-04-23
2016103  Internacional  Flamengo  2023-04-23
...                ...       ...         ...
2058422       Cruzeiro    Grêmio  2023-04-23
2058423       Cruzeiro    Grêmio  2023-04-23
2058424       Cruzeiro    Grêmio  2023-04-23
2058425       Cruzeiro    Grêmio  2023-04-23
2058426       Cruzeiro    Grêmio  2023-04-23

[1333 rows x 10 columns]
2023-04-24
          GameId     Sportsbook Market Scenario   Bet     Odd  public_prob  \
2006561  7290356      Stake.com    h2h           home    2.07     0.483092
2006562  7290356      Stake.com    h2h           draw    3.00     0.333333
2006563  7290356      Stake.com    h2h           away    3.55     0.281690
2006564  7290356  BC.Game Sport    h2h           home    2.14     0.467290
2006565  7290356  BC.Game Sport    h2h           draw    3.30     0.303030
...          ...            ...    ...      ...   ...     ...          ...
2006815  7290356        Midnite  exact   10 : 6     o  101.00     0.009901
2006816  7290356        Midnite  exact   10 : 7     o  101.00     0.009901
2006817  7290356        Midnite  exact   10 : 8     o  101.00     0.009901
2006818  7290356        Midnite  exact   10 : 9     o  101.00     0.009901
2006819  7290356        Midnite  exact  10 : 10     o  101.00     0.009901

          Home      Away    Datetime
2006561  Bahia  Botafogo  2023-04-24
2006562  Bahia  Botafogo  2023-04-24
2006563  Bahia  Botafogo  2023-04-24
2006564  Bahia  Botafogo  2023-04-24
2006565  Bahia  Botafogo  2023-04-24
...        ...       ...         ...
2006815  Bahia  Botafogo  2023-04-24
2006816  Bahia  Botafogo  2023-04-24
2006817  Bahia  Botafogo  2023-04-24
2006818  Bahia  Botafogo  2023-04-24
2006819  Bahia  Botafogo  2023-04-24

[259 rows x 10 columns]
2023-04-29
          GameId     Sportsbook Market Scenario   Bet     Odd  public_prob  \
2060737  7290382      Stake.com    h2h           home    1.47     0.680272
2060738  7290382      Stake.com    h2h           draw    3.80     0.263158
2060739  7290382      Stake.com    h2h           away    7.00     0.142857
2060740  7290382  BC.Game Sport    h2h           home    1.48     0.675676
2060741  7290382  BC.Game Sport    h2h           draw    4.30     0.232558
...          ...            ...    ...      ...   ...     ...          ...
2100098  7290388        Midnite  exact   10 : 6     o  101.00     0.009901
2100099  7290388        Midnite  exact   10 : 7     o  101.00     0.009901
2100100  7290388        Midnite  exact   10 : 8     o  101.00     0.009901
2100101  7290388        Midnite  exact   10 : 9     o  101.00     0.009901
2100102  7290388        Midnite  exact  10 : 10     o  101.00     0.009901

              Home         Away    Datetime
2060737  Palmeiras  Corinthians  2023-04-29
2060738  Palmeiras  Corinthians  2023-04-29
2060739  Palmeiras  Corinthians  2023-04-29
2060740  Palmeiras  Corinthians  2023-04-29
2060741  Palmeiras  Corinthians  2023-04-29
...            ...          ...         ...
2100098  Fortaleza   Fluminense  2023-04-29
2100099  Fortaleza   Fluminense  2023-04-29
2100100  Fortaleza   Fluminense  2023-04-29
2100101  Fortaleza   Fluminense  2023-04-29
2100102  Fortaleza   Fluminense  2023-04-29

[1123 rows x 10 columns]
2023-04-30
          GameId      Sportsbook Market Scenario   Bet     Odd  public_prob  \
2069437  7290380       Stake.com    h2h           home    1.61     0.621118
2069438  7290380       Stake.com    h2h           draw    3.60     0.277778
2069439  7290380       Stake.com    h2h           away    5.40     0.185185
2069440  7290380   BC.Game Sport    h2h           home    1.61     0.621118
2069441  7290380   BC.Game Sport    h2h           draw    4.00     0.250000
...          ...             ...    ...      ...   ...     ...          ...
2043488  7290389           20Bet  exact    5 : 1     o  100.00     0.010000
2043489  7290389  LeoVegas Sport  exact    5 : 2     o  276.00     0.003623
2043490  7290389         Betobet  exact    5 : 3     o  451.00     0.002217
2043491  7290389           20Bet  exact    6 : 0     o  100.00     0.010000
2043492  7290389         Betobet  exact    6 : 1     o  501.00     0.001996

             Home      Away    Datetime
2069437  Flamengo  Botafogo  2023-04-30
2069438  Flamengo  Botafogo  2023-04-30
2069439  Flamengo  Botafogo  2023-04-30
2069440  Flamengo  Botafogo  2023-04-30
2069441  Flamengo  Botafogo  2023-04-30
...           ...       ...         ...
2043488    Cuiabá    Grêmio  2023-04-30
2043489    Cuiabá    Grêmio  2023-04-30
2043490    Cuiabá    Grêmio  2023-04-30
2043491    Cuiabá    Grêmio  2023-04-30
2043492    Cuiabá    Grêmio  2023-04-30

[935 rows x 10 columns]
2023-05-01
          GameId      Sportsbook Market Scenario   Bet     Odd  public_prob  \
2106157  7290381       Stake.com    h2h           home    1.77     0.564972
2106158  7290381       Stake.com    h2h           draw    3.30     0.303030
2106159  7290381       Stake.com    h2h           away    4.50     0.222222
2106160  7290381   BC.Game Sport    h2h           home    1.79     0.558659
2106161  7290381   BC.Game Sport    h2h           draw    3.70     0.270270
...          ...             ...    ...      ...   ...     ...          ...
2106371  7290381           20Bet  exact    6 : 0     o  100.00     0.010000
2106372  7290381  LeoVegas Sport  exact    6 : 1     o  226.00     0.004425
2106373  7290381         Betobet  exact    6 : 2     o  301.00     0.003322
2106374  7290381         Betobet  exact    7 : 0     o  501.00     0.001996
2106375  7290381         Betobet  exact    7 : 1     o  501.00     0.001996

                  Home   Away    Datetime
2106157  Vasco da Gama  Bahia  2023-05-01
2106158  Vasco da Gama  Bahia  2023-05-01
2106159  Vasco da Gama  Bahia  2023-05-01
2106160  Vasco da Gama  Bahia  2023-05-01
2106161  Vasco da Gama  Bahia  2023-05-01
...                ...    ...         ...
2106371  Vasco da Gama  Bahia  2023-05-01
2106372  Vasco da Gama  Bahia  2023-05-01
2106373  Vasco da Gama  Bahia  2023-05-01
2106374  Vasco da Gama  Bahia  2023-05-01
2106375  Vasco da Gama  Bahia  2023-05-01

[219 rows x 10 columns]
2023-05-06
          GameId     Sportsbook Market Scenario   Bet     Odd  public_prob  \
2047723  7290341      Stake.com    h2h           home    1.68     0.595238
2047724  7290341      Stake.com    h2h           draw    3.25     0.307692
2047725  7290341      Stake.com    h2h           away    5.40     0.185185
2047726  7290341  BC.Game Sport    h2h           home    1.70     0.588235
2047727  7290341  BC.Game Sport    h2h           draw    3.60     0.277778
...          ...            ...    ...      ...   ...     ...          ...
2048025  7290341          1xBet  exact   10 : 6     o  500.00     0.002000
2048026  7290341          1xBet  exact   10 : 7     o  500.00     0.002000
2048027  7290341          1xBet  exact   10 : 8     o  500.00     0.002000
2048028  7290341          1xBet  exact   10 : 9     o  500.00     0.002000
2048029  7290341          1xBet  exact  10 : 10     o  500.00     0.002000

             Home    Away    Datetime
2047723  Cruzeiro  Santos  2023-05-06
2047724  Cruzeiro  Santos  2023-05-06
2047725  Cruzeiro  Santos  2023-05-06
2047726  Cruzeiro  Santos  2023-05-06
2047727  Cruzeiro  Santos  2023-05-06
...           ...     ...         ...
2048025  Cruzeiro  Santos  2023-05-06
2048026  Cruzeiro  Santos  2023-05-06
2048027  Cruzeiro  Santos  2023-05-06
2048028  Cruzeiro  Santos  2023-05-06
2048029  Cruzeiro  Santos  2023-05-06

[307 rows x 10 columns]
2023-05-07
          GameId     Sportsbook Market Scenario   Bet     Odd  public_prob  \
2068393  7290338      Stake.com    h2h           home    2.06     0.485437
2068394  7290338      Stake.com    h2h           draw    3.05     0.327869
2068395  7290338      Stake.com    h2h           away    3.60     0.277778
2068396  7290338  BC.Game Sport    h2h           home    2.09     0.478469
2068397  7290338  BC.Game Sport    h2h           draw    3.40     0.294118
...          ...            ...    ...      ...   ...     ...          ...
2074878  7290391          1xBet  exact   10 : 6     o  500.00     0.002000
2074879  7290391          1xBet  exact   10 : 7     o  500.00     0.002000
2074880  7290391          1xBet  exact   10 : 8     o  500.00     0.002000
2074881  7290391          1xBet  exact   10 : 9     o  500.00     0.002000
2074882  7290391          1xBet  exact  10 : 10     o  500.00     0.002000

              Home              Away    Datetime
2068393  São Paulo     Internacional  2023-05-07
2068394  São Paulo     Internacional  2023-05-07
2068395  São Paulo     Internacional  2023-05-07
2068396  São Paulo     Internacional  2023-05-07
2068397  São Paulo     Internacional  2023-05-07
...            ...               ...         ...
2074878   Botafogo  Atlético Mineiro  2023-05-07
2074879   Botafogo  Atlético Mineiro  2023-05-07
2074880   Botafogo  Atlético Mineiro  2023-05-07
2074881   Botafogo  Atlético Mineiro  2023-05-07
2074882   Botafogo  Atlético Mineiro  2023-05-07

[2462 rows x 10 columns]
2023-05-08
          GameId     Sportsbook Market Scenario   Bet     Odd  public_prob  \
2046232  7290339      Stake.com    h2h           home    2.55     0.392157
2046233  7290339      Stake.com    h2h           draw    2.85     0.350877
2046234  7290339      Stake.com    h2h           away    2.75     0.363636
2046235  7290339  BC.Game Sport    h2h           home    2.60     0.384615
2046236  7290339  BC.Game Sport    h2h           draw    3.15     0.317460
...          ...            ...    ...      ...   ...     ...          ...
2046530  7290339          1xBet  exact   10 : 6     o  500.00     0.002000
2046531  7290339          1xBet  exact   10 : 7     o  500.00     0.002000
2046532  7290339          1xBet  exact   10 : 8     o  500.00     0.002000
2046533  7290339          1xBet  exact   10 : 9     o  500.00     0.002000
2046534  7290339          1xBet  exact  10 : 10     o  500.00     0.002000

                Home       Away    Datetime
2046232  Corinthians  Fortaleza  2023-05-08
2046233  Corinthians  Fortaleza  2023-05-08
2046234  Corinthians  Fortaleza  2023-05-08
2046235  Corinthians  Fortaleza  2023-05-08
2046236  Corinthians  Fortaleza  2023-05-08
...              ...        ...         ...
2046530  Corinthians  Fortaleza  2023-05-08
2046531  Corinthians  Fortaleza  2023-05-08
2046532  Corinthians  Fortaleza  2023-05-08
2046533  Corinthians  Fortaleza  2023-05-08
2046534  Corinthians  Fortaleza  2023-05-08

[303 rows x 10 columns]
2023-05-10
          GameId     Sportsbook Market Scenario   Bet     Odd  public_prob  \
2041572  7290321      Stake.com    h2h           home    3.50     0.285714
2041573  7290321      Stake.com    h2h           draw    2.95     0.338983
2041574  7290321      Stake.com    h2h           away    2.13     0.469484
2041575  7290321  BC.Game Sport    h2h           home    3.55     0.281690
2041576  7290321  BC.Game Sport    h2h           draw    3.25     0.307692
...          ...            ...    ...      ...   ...     ...          ...
2063407  7290352          1xBet  exact   10 : 6     o  500.00     0.002000
2063408  7290352          1xBet  exact   10 : 7     o  500.00     0.002000
2063409  7290352          1xBet  exact   10 : 8     o  500.00     0.002000
2063410  7290352          1xBet  exact   10 : 9     o  500.00     0.002000
2063411  7290352          1xBet  exact  10 : 10     o  500.00     0.002000

                  Home              Away    Datetime
2041572         Cuiabá  Atlético Mineiro  2023-05-10
2041573         Cuiabá  Atlético Mineiro  2023-05-10
2041574         Cuiabá  Atlético Mineiro  2023-05-10
2041575         Cuiabá  Atlético Mineiro  2023-05-10
2041576         Cuiabá  Atlético Mineiro  2023-05-10
...                ...               ...         ...
2063407  Internacional      Athletico-PR  2023-05-10
2063408  Internacional      Athletico-PR  2023-05-10
2063409  Internacional      Athletico-PR  2023-05-10
2063410  Internacional      Athletico-PR  2023-05-10
2063411  Internacional      Athletico-PR  2023-05-10

[1563 rows x 10 columns]
2023-05-11
          GameId     Sportsbook Market Scenario   Bet     Odd  public_prob  \
2005750  7290320      Stake.com    h2h           home    1.95     0.512821
2005751  7290320      Stake.com    h2h           draw    3.10     0.322581
2005752  7290320      Stake.com    h2h           away    3.85     0.259740
2005753  7290320  BC.Game Sport    h2h           home    1.98     0.505051
2005754  7290320  BC.Game Sport    h2h           draw    3.45     0.289855
...          ...            ...    ...      ...   ...     ...          ...
2050784  7290353          1xBet  exact   10 : 6     o  500.00     0.002000
2050785  7290353          1xBet  exact   10 : 7     o  500.00     0.002000
2050786  7290353          1xBet  exact   10 : 8     o  500.00     0.002000
2050787  7290353          1xBet  exact   10 : 9     o  500.00     0.002000
2050788  7290353          1xBet  exact  10 : 10     o  500.00     0.002000

              Home           Away    Datetime
2005750  Fortaleza      São Paulo  2023-05-11
2005751  Fortaleza      São Paulo  2023-05-11
2005752  Fortaleza      São Paulo  2023-05-11
2005753  Fortaleza      São Paulo  2023-05-11
2005754  Fortaleza      São Paulo  2023-05-11
...            ...            ...         ...
2050784   Coritiba  Vasco da Gama  2023-05-11
2050785   Coritiba  Vasco da Gama  2023-05-11
2050786   Coritiba  Vasco da Gama  2023-05-11
2050787   Coritiba  Vasco da Gama  2023-05-11
2050788   Coritiba  Vasco da Gama  2023-05-11

[1526 rows x 10 columns]
2023-05-13
          GameId     Sportsbook Market Scenario   Bet     Odd  public_prob  \
2108954  7290322      Stake.com    h2h           home    1.40     0.714286
2108955  7290322      Stake.com    h2h           draw    4.30     0.232558
2108956  7290322      Stake.com    h2h           away    7.40     0.135135
2108957  7290322  BC.Game Sport    h2h           home    1.41     0.709220
2108958  7290322  BC.Game Sport    h2h           draw    4.80     0.208333
...          ...            ...    ...      ...   ...     ...          ...
2052983  7290330          1xBet  exact   10 : 6     o  500.00     0.002000
2052984  7290330          1xBet  exact   10 : 7     o  500.00     0.002000
2052985  7290330          1xBet  exact   10 : 8     o  500.00     0.002000

In [35]:
# Function to get the n-th group and its DataFrame
def get_nth_group(grouped, n):
    for i, (group_key, group_df) in enumerate(grouped):
        if i == n:
            return group_key, group_df
    raise IndexError("Group index out of range")
n = 0
group = get_nth_group(grouped, n)

In [36]:
date, group_data = group
print(date)

2023-04-15

In [37]:
games_ids = group_data.GameId.unique()
print(games_ids)

['7290394' '7290395' '7290397' '7290400' '7290401' '7290402']

In [38]:
odds[odds.GameId=="7290395"]

,GameId,Sportsbook,Market,Scenario,Bet,Odd,public_prob,Home,Away,Datetime
2039271,7290395,Stake.com,h2h,,home,1.36,0.735294,Palmeiras,Cuiabá,2023-04-15
2039272,7290395,Stake.com,h2h,,draw,4.90,0.204082,Palmeiras,Cuiabá,2023-04-15
2039273,7290395,Stake.com,h2h,,away,8.20,0.121951,Palmeiras,Cuiabá,2023-04-15
2039274,7290395,BC.Game Sport,h2h,,home,1.36,0.735294,Palmeiras,Cuiabá,2023-04-15
2039275,7290395,BC.Game Sport,h2h,,draw,5.00,0.200000,Palmeiras,Cuiabá,2023-04-15
...,...,...,...,...,...,...,...,...,...,...
2039519,7290395,Midnite,exact,10 : 6,o,101.00,0.009901,Palmeiras,Cuiabá,2023-04-15
2039520,7290395,Midnite,exact,10 : 7,o,101.00,0.009901,Palmeiras,Cuiabá,2023-04-15
2039521,7290395,Midnite,exact,10 : 8,o,101.00,0.009901,Palmeiras,Cuiabá,2023-04-15
2039522,7290395,Midnite,exact,10 : 9,o,101.00,0.009901,Palmeiras,Cuiabá,2023-04-15
2039523,7290395,Midnite,exact,10 : 10,o,101.00,0.009901,Palmeiras,Cuiabá,2023-04-15

In [25]:
# metadata, gameid_to_outcome = load_metadata_artefacts("data/metadata-with-date-new.parquet")
# odds = load_odds("data/odds-new-correct.parquet")
# odds = join_metadata(odds, metadata)
# print(metadata.shape)
# print(odds.shape)

In [26]:
# from data import load_map
# data = load_map("data/meanSurface-new.json")

In [27]:
GAME_ID = "7290395" # Chapecoense x Flamengo
my_game = GameProbs(GAME_ID) 
df = my_game.build_dataframe()
df

        0       1       2       3       4       5       6
0  0.0245  0.0006  0.0017  0.0035  0.0058  0.0085  0.1814
1  0.0002  0.0250  0.0029  0.0057  0.0093  0.0130  0.2223
2  0.0002  0.0011  0.0146  0.0054  0.0085  0.0116  0.1732
3  0.0002  0.0009  0.0022  0.0078  0.0061  0.0081  0.1089
4  0.0001  0.0006  0.0014  0.0025  0.0047  0.0049  0.0602
5  0.0001  0.0003  0.0008  0.0014  0.0021  0.0029  0.0306
6  0.0001  0.0004  0.0009  0.0015  0.0021  0.0026  0.0264

In [28]:
group_data

,GameId,Sportsbook,Market,Scenario,Bet,Odd,public_prob,Home,Away,Datetime
56978,2782628,Bet365,h2h,,home,1.45,0.689655,Flamengo,Fortaleza,2019-06-01
56979,2782628,Bet365,h2h,,draw,4.00,0.250000,Flamengo,Fortaleza,2019-06-01
56980,2782628,Bet365,h2h,,away,7.50,0.133333,Flamengo,Fortaleza,2019-06-01
56981,2782628,Bet365,over/under,0.5,over,1.06,0.943396,Flamengo,Fortaleza,2019-06-01
56982,2782628,Bet365,over/under,0.5,under,10.00,0.100000,Flamengo,Fortaleza,2019-06-01
...,...,...,...,...,...,...,...,...,...,...
59081,2782629,NordicBet,exact,5 : 0,o,175.00,0.005714,Bahia,Grêmio,2019-06-01
59082,2782629,NordicBet,exact,5 : 1,o,200.00,0.005000,Bahia,Grêmio,2019-06-01
59083,2782629,NordicBet,exact,6 : 0,o,250.00,0.004000,Bahia,Grêmio,2019-06-01
59084,2782629,NordicBet,both_score,,yes,2.26,0.442478,Bahia,Grêmio,2019-06-01
59085,2782629,NordicBet,both_score,,no,1.58,0.632911,Bahia,Grêmio,2019-06-01

In [15]:
GAME_ID = '7290395'
odds_sample = group_data[(group_data.GameId==GAME_ID)]
#odds_sample = group_data
#odds_sample = join_metadata(odds_sample, metadata)
games_ids = odds_sample['GameId'].unique()
print(games_ids)

# Initialize dict to store dataframes of favorable bet opportunities
odds_dict = {}
# Initialize dict to store 7x7 matrices/dataframes of real probabilities 
df_probs_dict = {}

for game_id in games_ids:
    df = GameProbs(game_id).build_dataframe()
    odds_sample = group_data[(group_data.GameId==game_id)]
    odds_sample = apply_final_treatment(df_odds=odds_sample, df_real_prob=df)
    odds_sample = filter_by_linear_combination(odds_sample, n=5)
    odds_dict[game_id] = odds_sample
    df_probs_dict[game_id] = df
odds_dt = pd.concat(odds_dict.values())

[]

ValueError: No objects to concatenate

In [14]:
len(df_probs_dict.values())

2

In [15]:
odds_sample = odds_sample[odds_sample.Market.isin(['spread', 'over/under', 'h2h', 'exact', 'both_score'])].reset_index(drop=True)
print(odds_sample.shape)

(4, 17)

In [16]:
n = len(odds_dt)
allocation_array = np.round(np.array(((1/n), ) * n), 4)
allocation_array

array([0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111,
       0.1111])

## COBYLA via Simulation Optimizer

In [17]:
from monte_carlo_return import (
    generate_bet_return,
    compute_objective_via_simulation,
)

In [18]:
games_ids

array(['2782628', '2782629'], dtype=object)

In [19]:
len(odds_dict)

2

In [20]:
n = len(odds_dt)
allocation_array = np.round(np.array(((1/n), ) * n), 4)
allocation_array

financial_return_array = generate_bet_return(
    df_prob=df_probs_dict,
    df_bet=odds_dt,
    num_simulations=10000,
    allocation_array=allocation_array
)
financial_return_array

array([0.687709 , 1.870924 , 1.3859725, ..., 0.6460465, 3.249675 ,
       1.3859725])

In [21]:
print(np.mean(financial_return_array))
print(np.std(financial_return_array))

1.1726516120000001
2.3527541642281093

In [22]:
games_ids

array(['2782628', '2782629'], dtype=object)

In [23]:
compute_objective_via_simulation(
    x=allocation_array,
    df_prob=df_probs_dict,
    df_bet=odds_dt,
    num_simulations=10000
)

-0.48073276322967534

In [24]:
solution, value, time_limit_flag = Optimizer().run_optimization(
    fun=compute_objective_via_simulation,
    x0=np.zeros(len(odds_dt)),
    args=(df_probs_dict, odds_dt, 1000),
)
print(f"Value: {value}")

Value: -3.924314369779696
   Normal return from subroutine COBYLA


   NFVALS =  114   F =-3.924314E+00    MAXCV = 0.000000E+00
   X = 1.488675E+00   2.713398E+00   1.750020E+00   1.993636E+00  -1.666307E+00
       8.951997E-01  -5.212408E-01  -1.344915E+00  -2.914300E+00

In [26]:
value

-6.618251607544345

## COBYLA Analytical Optimizer

In [24]:
from analytical_return import compute_objective_via_analytical

In [25]:
odds_favorable = np.array(odds_dt['Odd'])
real_prob_favorable = np.array(odds_dt['real_prob'])
#scenario_favorable = np.array(odds_sample_favorable['Bet'])
event_favorable = list(odds_dt['BetMap'].values)
games_ids = np.array(odds_dt['GameId'])

In [26]:
len(games_ids)

9

In [31]:
# n = len(odds_dt)
# allocation_array = np.round(np.array(((1/n), ) * n), 4)
# allocation_array

In [32]:
allocation_array

array([0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111,
       0.1111])

In [33]:
compute_objective_via_analytical(
    x=np.zeros(len(odds_dt)),
    public_odd=odds_favorable,
    real_probabilities=real_prob_favorable,
    event=event_favorable,
    games_ids=games_ids,
    df_probs_dict=df_probs_dict,
)

-0.48152068573464457

In [34]:
solution, value, time_limit_flag = Optimizer().run_optimization(
    fun=compute_objective_via_analytical,
    x0=np.zeros(len(odds_favorable)),
    args=(odds_favorable, real_prob_favorable, event_favorable, games_ids, df_probs_dict)
)
print(f"Value: {value}")

Value: -6.965906207766195
   Return from subroutine COBYLA because the MAXFUN limit has been reached.


   NFVALS = 1000   F =-6.965906E+00    MAXCV = 0.000000E+00
   X = 4.572379E+00   2.105247E+00   1.509035E+00   2.129818E+00  -2.443923E-01
       3.172832E-01  -1.435522E+00  -2.498112E+00  -3.376482E+00

## LongTermOptimizer

In [27]:
len(odds_favorable) == len(odds_dt)

True

In [28]:
from LongTermOptimizer import estimate_long_term_return
solution, value, time_limit_flag = Optimizer().run_optimization(
    fun=estimate_long_term_return,
    x0=np.zeros(len(odds_dt)),
    args=(df_probs_dict, odds_dt, 100)
)
print(f"Value: {value}")

Value: -1.5048704186575604e+16
   Normal return from subroutine COBYLA


   NFVALS =   87   F =-1.504870E+16    MAXCV = 0.000000E+00
   X = 7.702248E-01   3.335832E+00   1.214765E+00  -5.862824E-01  -2.318410E+00
       1.001839E+00  -5.676557E-01  -7.775075E-02  -6.495089E-01

In [30]:
from dependencies.utils import softmax
assert len(solution) == len(odds_dt)
print(f"Sum of solution: {sum(solution)}")
solution = softmax(solution)
print(f"Sum of solution after softmax: {sum(solution)}")
print(solution)

Sum of solution: 2.123054062013594
Sum of solution after softmax: 1.0
[0.05535704 0.72011537 0.0863444  0.01425769 0.0025223  0.06978494
 0.01452575 0.02370837 0.01338414]